version: "3.8"

services:
  kurupdevs:
    build: .
    container_name: kurupdevs
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Kolkata  # Set timezone
    logging:
      driver: json-file  # Log for debugging
      options:
        max-size: "10m"
        max-file: "3"
